spring:
  data:
    mongodb:
      database: BlogReactive
      host: vs
      port: 10.131.155.57
      username: root
      password: admin
      authentication-database: admin
      
server:
  port: 8086
