spring:
  data:
    mongodb:
      database: BlogReactive
      host: vs
      port: 27017
      #username: root
      #password: admin
      #authentication-database: admin
      
server:
  port: 8086
